/* components.js
   Provides shared sample data and rendering helpers for stories, genres, navbar, and footer.
   Exposes global `Components` object.
*/
(function(global){
  const stories = [
    {id:'s1',title:'The Last Sunrise',author:'A. Rahman',reads:'12.3k',genre:'Fantasy',cover:'https://picsum.photos/seed/story1/420/600',desc:'A journey begins at the end of a world.' ,chapters: 28},
    {id:'s2',title:'Moonlight & Roses',author:'S. Putri',reads:'8.6k',genre:'Romance',cover:'https://picsum.photos/seed/story2/420/600',desc:'Love in the shadow of the moon.',chapters: 18},
    {id:'s3',title:'Shadows of Elden',author:'R. Kurnia',reads:'21.1k',genre:'Fantasy',cover:'https://picsum.photos/seed/story3/420/600',desc:'A dark kingdom, a brighter hope.',chapters: 42},
    {id:'s4',title:'Midnight Confessions',author:'L. Ardi',reads:'6.4k',genre:'Drama',cover:'https://picsum.photos/seed/story4/420/600',desc:'Secrets told at 00:00.',chapters: 12},
    {id:'s5',title:'Echoes of Home',author:'I. Sari',reads:'3.9k',genre:'Slice of Life',cover:'https://picsum.photos/seed/story5/420/600',desc:'Small moments that matter.',chapters: 9},
    {id:'s6',title:'Neon City Nights',author:'K. Yusuf',reads:'7.9k',genre:'Sci-Fi',cover:'https://picsum.photos/seed/story6/420/600',desc:'A neon metropolis with many faces.',chapters: 21},
    {id:'s7',title:'Under the Bed',author:'M. Hana',reads:'4.6k',genre:'Horror',cover:'https://picsum.photos/seed/story7/420/600',desc:'Not all monsters are imaginary.',chapters: 7},
    {id:'s8',title:'Letters to Tomorrow',author:'P. Dwi',reads:'2.1k',genre:'Romance',cover:'https://picsum.photos/seed/story8/420/600',desc:'Postcards for future selves.',chapters: 15}
  ];

  // Ensure we have at least N stories by generating additional dummy entries if needed
  (function ensureManyStories(targetCount){
    if(stories.length >= targetCount) return;
    const baseSeeds = [
      'Crimson Tide','Glass Harbor','Wildflower Days','Orbit of Souls','Paper Lanterns','Rust & Stardust','Quiet Harbor','Blue Velvet Nights',
      'Fading Polaroids','Silver Orchard','The Paper Gate','Lost Atlas','Velvet Requiem','City of Ashes','Whispering Pines','Sunday Letters'
    ];
    let idx = 1;
    while(stories.length < targetCount){
      const seed = baseSeeds[(stories.length) % baseSeeds.length];
      const id = 'gen' + (stories.length + 1);
      const title = `${seed} ${idx}`;
      const author = `Author ${String.fromCharCode(65 + (stories.length % 26))}`;
      const reads = `${Math.floor(500 + Math.random()*30000)}k`;
      const genreOptions = ['Romance','Fantasy','Horror','Mystery','Sci-Fi','Slice of Life','Drama','Comics'];
      const genre = genreOptions[stories.length % genreOptions.length];
      const cover = `https://picsum.photos/seed/${encodeURIComponent(id)}/420/600`;
      const desc = `An autogenerated short blurb for ${title}.`;
      const chapters = Math.floor(5 + Math.random()*60);
      stories.push({id,title,author,reads,genre,cover,desc,chapters});
      idx++;
    }
  })(40);

  const genres = [
    {id:'g1',name:'Romance',color:'#ffd6e0'},
    {id:'g2',name:'Fantasy',color:'#e8ddff'},
    {id:'g3',name:'Horror',color:'#ffe4e1'},
    {id:'g4',name:'Mystery',color:'#e6f2ff'},
    {id:'g5',name:'Sci-Fi',color:'#e1f7ff'},
    {id:'g6',name:'Slice of Life',color:'#fff5d6'},
    {id:'g7',name:'Comics',color:'#f0ffe6'},
    {id:'g8',name:'Fanfiction',color:'#f9e6ff'}
  ];

  function createStoryCard(story){
    return `
      <a class="story-link" href="story.html?id=${story.id}">
        <article class="story-card" data-id="${story.id}" data-genre="${story.genre}">
          <img loading="lazy" src="${story.cover}" alt="cover of ${escapeHtml(story.title)}" class="card-cover">
          <div class="card-body">
            <h3 class="card-title">${escapeHtml(story.title)}</h3>
            <p class="card-meta">${escapeHtml(story.author)}</p>
            <p class="card-excerpt">${escapeHtml(story.desc || '')}</p>
          </div>
        </article>
      </a>
    `;
  }

  function createStoryTile(story){
    return `
      <a class="story-link" href="story.html?id=${story.id}">
        <article class="story-tile" data-id="${story.id}" data-genre="${story.genre}">
          <div class="tile-cover-wrap">
            <img loading="lazy" src="${story.cover}" alt="cover of ${escapeHtml(story.title)}" class="tile-cover">
          </div>
          <div class="tile-body">
            <h4 class="tile-title">${escapeHtml(story.title)}</h4>
            <p class="tile-meta">${escapeHtml(story.author)}</p>
            <p class="tile-excerpt">${escapeHtml(story.desc || '')}</p>
          </div>
        </article>
      </a>
    `;
  }

  function renderStories(containerSelector, options){
    // Backwards-compatible: render carousel style (horizontal) using story-card
    const container = document.querySelector(containerSelector);
    if(!container) return;
    options = options || {};
    const q = (options.query||'').trim().toLowerCase();
    const genre = options.genre || '';
    let list = stories.slice();
    if(genre){
      list = list.filter(s => s.genre.toLowerCase() === genre.toLowerCase());
    }
    if(q){
      list = list.filter(s => (
        s.title.toLowerCase().includes(q) ||
        s.author.toLowerCase().includes(q) ||
        s.genre.toLowerCase().includes(q)
      ));
    }
    container.innerHTML = list.map(createStoryCard).join('\n');
  }

  function renderStoriesGrid(containerSelector, options){
    // Renders stories in a responsive grid. Supports pagination via limit/offset and append flag.
    const container = document.querySelector(containerSelector);
    if(!container) return;
    options = options || {};
    const q = (options.query||'').trim().toLowerCase();
    const genre = options.genre || '';
    const limit = options.limit != null ? options.limit : 12;
    const offset = options.offset != null ? options.offset : 0;
    const append = !!options.append;

    let list = stories.slice();
    if(genre){
      list = list.filter(s => s.genre.toLowerCase() === genre.toLowerCase());
    }
    if(q){
      list = list.filter(s => (
        s.title.toLowerCase().includes(q) ||
        s.author.toLowerCase().includes(q) ||
        s.genre.toLowerCase().includes(q)
      ));
    }
    const slice = list.slice(offset, offset + limit);
    const html = slice.map(createStoryTile).join('\n');
    if(append){
      container.insertAdjacentHTML('beforeend', html);
    } else {
      container.innerHTML = html;
    }
    return { total: list.length, rendered: slice.length };
  }

  function createGenreCard(genre){
    // link to genre page with query param
    return `
      <a class="genre" href="genre.html?genre=${encodeURIComponent(genre.name)}" style="background:${genre.color};">
        ${escapeHtml(genre.name)}
      </a>
    `;
  }

  function renderGenres(containerSelector){
    const container = document.querySelector(containerSelector);
    if(!container) return;
    container.innerHTML = genres.map(createGenreCard).join('\n');
  }

  /* Small hero slider items (compact cards) */
  function createHeroSlide(story){
    return `
      <a class="story-link" href="story.html?id=${story.id}">
        <article class="hero-card" data-id="${story.id}">
          <img loading="lazy" src="${story.cover}" alt="cover of ${escapeHtml(story.title)}" class="hero-cover">
          <div class="hero-card-title">${escapeHtml(story.title)}</div>
        </article>
      </a>
    `;
  }

  function renderHeroSlider(containerSelector, count){
    const container = document.querySelector(containerSelector);
    if(!container) return;
    count = typeof count === 'number' ? Math.max(6, Math.min(20, count)) : 12;
    const list = stories.slice(0, count);
    container.innerHTML = list.map(createHeroSlide).join('\n');
  }

  function getStoryById(id){
    return stories.find(s => s.id === id) || null;
  }

  function renderStoryDetail(targetSelector, id){
    const target = document.querySelector(targetSelector);
    if(!target) return;
    const story = getStoryById(id);
    if(!story){
      target.innerHTML = '<p>Story not found.</p>';
      return;
    }
    target.innerHTML = `
      <div class="story-detail">
        <div class="detail-left">
          <img loading="lazy" src="${story.cover}" alt="${escapeHtml(story.title)} cover" class="detail-cover">
        </div>
        <div class="detail-right">
          <h1 id="modal-title">${escapeHtml(story.title)}</h1>
          <p class="muted">by ${escapeHtml(story.author)} • ${escapeHtml(story.reads)} reads • ${story.chapters} chapters</p>
          <p class="story-desc">${escapeHtml(story.desc)}</p>
          <div class="detail-actions">
            <a class="btn btn-primary" href="#">Mulai Baca</a>
            <button class="btn-secondary" type="button">Tambah ke Koleksi</button>
          </div>
        </div>
      </div>
      <section class="comments">
        <h3>Comments</h3>
        <div class="comment">This is a dummy comment area. Add your own comments here.</div>
      </section>
    `;
  }

  function escapeHtml(str){
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  // Expose API
  global.Components = {
    renderStories,
    renderStoriesGrid,
    renderGenres,
    renderHeroSlider,
    renderStoryDetail,
    getStoryById,
    getAllStories: () => stories.slice(),
    getAllGenres: () => genres.slice()
  };
})(window);
